<?php $images = $block->getImages() ?>
<div class="slide-show" data-mage-init='
{
"AAllen_Images/js/slideshow":
    {
        "images": <?php echo json_encode($images) ?>,
        "duration": <?php echo $block->getDuration() ?>,
        "fadeLength": <?php echo $block->getFadeLength() ?>
    }
}'>
    <!--A placeholder needed by Chrome-->
    <div style="position: absolute; opacity: 0; height: 100%; width: 5px"></div>

    <div class="slide-show-image-wrapper">
        <img src="<?php echo current($images) ?>">
    </div>
</div>
