<div class="tiered-background one" data-mage-init='{"AAllen_TieredBackground/js/scroll":{}}'>
    <img src="<?php echo $block->getViewFileUrl('AAllen_TieredBackground::images/cloud.png')?>">
</div>
<div class="tiered-background two" data-mage-init='{"AAllen_TieredBackground/js/scroll":{}}'>
    <img src="<?php echo $block->getViewFileUrl('AAllen_TieredBackground::images/cloud.png')?>">
</div>
<div class="tiered-background three" data-mage-init='{"AAllen_TieredBackground/js/scroll":{}}'>
    <img src="<?php echo $block->getViewFileUrl('AAllen_TieredBackground::images/cloud.png')?>">
</div>