<!-- #region Jssor Slider Begin -->
<!-- Generator: Jssor Slider Maker -->
<!-- Source: https://www.jssor.com -->

<div class="slide-show" id="jssor_1" style="position:relative;margin:0 auto;top:0px;left:0px;width:<?php echo $block->getWidth() ?>px;height:<?php echo $block->getHeight() ?>px;overflow:hidden;visibility:hidden;">
    <!-- Loading Screen -->
    <div data-u="loading" class="jssorl-004-double-tail-spin" style="position:absolute;top:0px;left:0px;text-align:center;background-color:rgba(0,0,0,0.7);">
        <img style="margin-top:-19px;position:relative;top:50%;width:38px;height:38px;" src="<?php echo $block->getViewFileUrl('AAllen_Images::images/double-tail-spin.svg') ?>" />
    </div>
    <div data-u="slides" style="cursor:default;position:relative;top:0px;left:0px;width:998px;height:439px;overflow:hidden;">
        <?php foreach ($block->getImageUrls() as $imageUrl): ?>
            <div>
                <img data-u="image" src="<?php echo $imageUrl ?>">
            </div>
        <?php endforeach; ?>
        <a data-u="any" href="https://www.jssor.com" style="display:none">carousel html</a>
    </div>
</div>
<!-- #endregion Jssor Slider End -->

<script type="text/x-magento-init">
    {
        "*": {
            "AAllen_Images/js/jssor-init": {
                "duration": "<?php echo $block->getDuration() ?>",
                "width": "<?php echo $block->getWidth() ?>"
            }
        }
    }
</script>
